// packages/svelte/src/lib/CadViewer.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import {
    CadViewer as CoreCadViewer,
    type CadViewerOptions,
    type FormatConverter,
    type DebugOptions,
    type DxfLayer,
    type SelectEvent,
    type MeasureEvent,
    type ViewTransform,
    type Tool,
    type Theme,
  } from '@cadview/core';

  interface Props {
    file?: File | ArrayBuffer | string | null;
    theme?: Theme;
    tool?: Tool;
    /** Enable debug overlay. Pass `true` for defaults, or a `DebugOptions` object. */
    debug?: boolean | DebugOptions;
    /** Enable off-main-thread DXF parsing via Web Worker. */
    worker?: boolean;
    options?: Omit<CadViewerOptions, 'theme' | 'initialTool' | 'debug' | 'worker'>;
    /** Format converters for non-DXF file formats (e.g. DWG via @cadview/dwg). */
    formatConverters?: FormatConverter[];
    class?: string;
    onselect?: (event: SelectEvent) => void;
    onmeasure?: (event: MeasureEvent) => void;
    onviewchange?: (transform: ViewTransform) => void;
    onlayersloaded?: (layers: DxfLayer[]) => void;
  }

  let {
    file = null,
    theme = 'dark',
    tool = 'pan',
    debug,
    worker,
    options = {},
    formatConverters,
    class: className = '',
    onselect,
    onmeasure,
    onviewchange,
    onlayersloaded,
  }: Props = $props();

  let canvas: HTMLCanvasElement;
  let viewer: CoreCadViewer | null = $state(null);

  // Initialize viewer — untrack reactive reads to prevent re-creation
  $effect(() => {
    if (!canvas) return;

    const initialTheme = untrack(() => theme);
    const initialTool = untrack(() => tool);
    const initialDebug = untrack(() => debug);
    const initialWorker = untrack(() => worker);
    const initialOptions = untrack(() => options);

    const initialConverters = untrack(() => formatConverters);

    const v = new CoreCadViewer(canvas, {
      theme: initialTheme,
      initialTool: initialTool,
      debug: initialDebug,
      worker: initialWorker,
      formatConverters: initialConverters,
      ...initialOptions,
    });
    viewer = v;

    return () => {
      v.destroy();
      viewer = null;
    };
  });

  // React to theme changes
  $effect(() => {
    viewer?.setTheme(theme);
  });

  // React to tool changes
  $effect(() => {
    viewer?.setTool(tool);
  });

  // React to debug changes
  $effect(() => {
    if (debug !== undefined) {
      viewer?.setDebug(debug);
    }
  });

  // React to file changes
  $effect(() => {
    if (!viewer || !file) return;
    const v = viewer;
    let cancelled = false;

    const load = async () => {
      try {
        if (file instanceof File) {
          await v.loadFile(file);
        } else if (file instanceof ArrayBuffer) {
          await v.loadBuffer(file);
        } else if (typeof file === 'string') {
          v.loadString(file);
        }
        if (!cancelled) {
          untrack(() => onlayersloaded)?.(v.getLayers());
        }
      } catch (err: unknown) {
        if (!cancelled) {
          console.error('CadViewer: failed to load file', err);
        }
      }
    };

    load();

    return () => {
      cancelled = true;
    };
  });

  // Event listener management
  $effect(() => {
    if (!viewer) return;
    const v = viewer;

    const cleanups: Array<() => void> = [];

    if (onselect) {
      v.on('select', onselect);
      cleanups.push(() => { v.off('select', onselect!); });
    }
    if (onmeasure) {
      v.on('measure', onmeasure);
      cleanups.push(() => { v.off('measure', onmeasure!); });
    }
    if (onviewchange) {
      v.on('viewchange', onviewchange);
      cleanups.push(() => { v.off('viewchange', onviewchange!); });
    }

    return () => { cleanups.forEach((c) => { c(); }); };
  });

  export function getViewer(): CoreCadViewer | null {
    return viewer;
  }

  export function fitToView(): void {
    viewer?.fitToView();
  }

  export function getLayers(): DxfLayer[] {
    return viewer?.getLayers() ?? [];
  }

  export function setLayerVisible(name: string, visible: boolean): void {
    viewer?.setLayerVisible(name, visible);
  }
</script>

<div class={className} style="position: relative; overflow: hidden;">
  <canvas
    bind:this={canvas}
    style="display: block; width: 100%; height: 100%;"
  ></canvas>
</div>

// packages/react/src/CadViewer.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
} from 'react';
import {
  CadViewer as CoreCadViewer,
  type CadViewerOptions,
  type FormatConverter,
  type DebugOptions,
  type DxfLayer,
  type SelectEvent,
  type MeasureEvent,
  type ViewTransform,
  type Tool,
  type Theme,
} from '@cadview/core';

export interface CadViewerProps {
  file?: File | ArrayBuffer | string | null;
  theme?: Theme;
  tool?: Tool;
  /** Enable debug overlay. Pass `true` for defaults, or a `DebugOptions` object. */
  debug?: boolean | DebugOptions;
  /** Enable off-main-thread DXF parsing via Web Worker. */
  worker?: boolean;
  className?: string;
  style?: CSSProperties;
  options?: Omit<CadViewerOptions, 'theme' | 'initialTool' | 'debug' | 'worker'>;
  /** Format converters for non-DXF file formats (e.g. DWG via @cadview/dwg). */
  formatConverters?: FormatConverter[];
  onSelect?: (event: SelectEvent) => void;
  onMeasure?: (event: MeasureEvent) => void;
  onViewChange?: (transform: ViewTransform) => void;
  onLayersLoaded?: (layers: DxfLayer[]) => void;
}

export interface CadViewerRef {
  getViewer(): CoreCadViewer | null;
  fitToView(): void;
  getLayers(): DxfLayer[];
  setLayerVisible(name: string, visible: boolean): void;
}

export const CadViewer = forwardRef<CadViewerRef, CadViewerProps>(
  function CadViewer(props, ref) {
    const {
      file,
      theme = 'dark',
      tool = 'pan',
      debug,
      worker,
      className,
      style,
      options,
      formatConverters,
      onSelect,
      onMeasure,
      onViewChange,
      onLayersLoaded,
    } = props;

    const canvasRef = useRef<HTMLCanvasElement>(null);
    const viewerRef = useRef<CoreCadViewer | null>(null);

    useEffect(() => {
      if (!canvasRef.current) return;

      const viewer = new CoreCadViewer(canvasRef.current, {
        theme,
        initialTool: tool,
        debug,
        worker,
        formatConverters,
        ...options,
      });
      viewerRef.current = viewer;

      return () => {
        viewer.destroy();
        viewerRef.current = null;
      };
    }, []);

    useEffect(() => {
      viewerRef.current?.setTheme(theme);
    }, [theme]);

    useEffect(() => {
      viewerRef.current?.setTool(tool);
    }, [tool]);

    useEffect(() => {
      if (debug !== undefined) {
        viewerRef.current?.setDebug(debug);
      }
    }, [debug]);

    useEffect(() => {
      const viewer = viewerRef.current;
      if (!viewer || !file) return;
      let cancelled = false;

      const load = async () => {
        try {
          if (file instanceof File) {
            await viewer.loadFile(file);
          } else if (file instanceof ArrayBuffer) {
            await viewer.loadBuffer(file);
          } else if (typeof file === 'string') {
            viewer.loadString(file);
          }
          if (!cancelled) {
            onLayersLoaded?.(viewer.getLayers());
          }
        } catch (err) {
          if (!cancelled) {
            console.error('CadViewer: failed to load file', err);
          }
        }
      };

      load();

      return () => {
        cancelled = true;
      };
    }, [file]);

    useEffect(() => {
      const viewer = viewerRef.current;
      if (!viewer) return;

      const handlers: Array<() => void> = [];

      if (onSelect) {
        viewer.on('select', onSelect);
        handlers.push(() => viewer.off('select', onSelect));
      }
      if (onMeasure) {
        viewer.on('measure', onMeasure);
        handlers.push(() => viewer.off('measure', onMeasure));
      }
      if (onViewChange) {
        viewer.on('viewchange', onViewChange);
        handlers.push(() => viewer.off('viewchange', onViewChange));
      }

      return () => { handlers.forEach((h) => { h(); }); };
    }, [onSelect, onMeasure, onViewChange]);

    useImperativeHandle(ref, () => ({
      getViewer: () => viewerRef.current,
      fitToView: () => viewerRef.current?.fitToView(),
      getLayers: () => viewerRef.current?.getLayers() ?? [],
      setLayerVisible: (name: string, visible: boolean) =>
        viewerRef.current?.setLayerVisible(name, visible),
    }));

    return (
      <div
        className={className}
        style={{ position: 'relative', overflow: 'hidden', ...style }}
      >
        <canvas
          ref={canvasRef}
          style={{ display: 'block', width: '100%', height: '100%' }}
        />
      </div>
    );
  },
);
